# Generated by Django 5.1.4 on 2025-01-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board1', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
