# Generated by Django 5.1.4 on 2025-01-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board1', '0003_alter_event_end_date_alter_event_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
